apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    workload: agent
  tolerations:
  - key: workload
    operator: Equal
    value: agent
    effect: NoSchedule
  securityContext:
    fsGroup: 1000
  containers:
  - name: maven
    image: docker.io/library/eclipse-temurin:21-jdk-alpine
    command:
    - sleep
    args:
    - infinity
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    securityContext:
      runAsUser: 1000
